### ISSUE TITLE
Provide dialog polyfill

### ISSUE THREAD

**Issue by willdurand** [Zoapp/react-materialcomponents#22]
We need a [dialog polyfill](https://github.com/GoogleChrome/dialog-polyfill) to
make this library work on all browsers. Currently, we do not ship it within
this lib but it would make sense to do so.

1. We should add the polyfill as a dependency
2. The CSS file should be concatenated (see `compile:css` npm script).
3. The JavaScript should be imported in `src/libs/dialog/index.js`

**Comment by mikbry** [comment]
DialogPolyfill is not correctly setup.
When
on Firefox open Demos, click on fab favorite
What
Nothing happen
Instead of
A dialog is open
