### ISSUE TITLE
How to replace ListItemContent and ListItemAction?

### ISSUE THREAD

**Issue by willdurand** [Zoapp/react-materialcomponents#25]
The `ServicesList` component in zoapp/front displays a `List`. Each item has a `ListItemContent` and a `ListItemAction` component. I don't find the equivalent components in this lib.

**Comment by mikbry** [comment]
This issue should be set in zoapp/front

**Comment by willdurand** [comment]
oki, see: https://github.com/Zoapp/front/issues/12.
