### ISSUE TITLE
Error when `Dialog` does not have a `actions` prop

### ISSUE THREAD

**Issue by willdurand** [Zoapp/react-materialcomponents#31]
According to the prop types definition, it should be possible to have a dialog without actions, but this causes an error because the `Dialog` tries to iterate over the actions (`.map()`). It should be possible to use a `Dialog` without actions.

**Comment by mikbry** [comment]
You should have actions or Buttons as children or nothing right. I don't see when this error occur. In DialogFooter it iterate over an empty a variable.
