### ISSUE TITLE
Select : prettier added a regression !!

### ISSUE THREAD

**Issue by mikbry** [Zoapp/react-materialcomponents#87]
For children mapping the code was previously:
`{Children.map(children, child => React.cloneElement(child, { role: "option" }))}`
But Prettier transformed to :
```
          {Children.map(children, (child) => {
            React.cloneElement(child, { role: "option" });
          })}
```
That's wrong !!! The children are not rendered

**Comment by willdurand** [comment]
are you sure it is prettier or it is just me that introduced the bug?
